<PL_RS, program, 0, 0>
<PL_RS, var, 0, 0>
<PL_RS, integer, 0, 0>
<PL_RS, real, 0, 0>
<PL_RS, begin, 0, 0>
<PL_RS, end, 0, 0>
<PL_RS, if, 0, 0>
<PL_RS, then, 0, 0>
<PL_RS, else, 0, 0>
<PL_RS, while, 0, 0>
<PL_RS, do, 0, 0>
